spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 781e629cfd181f1d40ef
            client-secret: 012020226d34032450ddca369b023fd2c5754cfd
          google:
            client-id: 781e629cfd181f1d40ef
            client-secret: 012020226d34032450ddca369b023fd2c5754cfd
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        show_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
server:
  port: 8081